version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${STORAGE}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment: 
      TZ: ${TZ} 
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - ${STORAGE}/pihole/etc:/etc/pihole
      - ${STORAGE}/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      PEERS: 5
    volumes:
      - ${STORAGE}/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/jellyfin:/config
      - ${STORAGE}/Movies:/data/movies
      - ${STORAGE}/Series:/data/tvshows
    ports:
      - 8096:8096
    restart: unless-stopped
