version: '3'
services:
  wireguard-transmission:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-transmission
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    ports:
      - 9091:9091/tcp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      - wireguard-transmission
    network_mode: service:wireguard-transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      USER: ${TRANSMISSION_USER}
      PASS: ${TRANSMISSION_PASS}
      PEERPORT: ${TRANSMISSION_PORT}
    volumes:
      - ${STORAGE}/transmission:/config
      - ${STORAGE}/Downloads:/downloads
      - ${STORAGE}/Torrents:/watch
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/jellyfin:/config
      - ${STORAGE}/Series:/data/tvshows
      - ${STORAGE}/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/radarr:/config
      - ${STORAGE}/Movies:/movies
      - ${STORAGE}/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/sonarr:/config
      - ${STORAGE}/Series:/tv
      - ${STORAGE}/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/lidarr:/config
      - ${STORAGE}/Music:/music
      - ${STORAGE}/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    volumes:
      - ${STORAGE}/readarr:/config
      - ${STORAGE}/Books:/books
      - ${STORAGE}/Downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
